version = 0.1

[default.deploy.parameters]
stack_name = "noqueue-backend"
resolve_s3 = true
s3_prefix = "noqueue-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MockDataBucket=\"noqueue-mock-data-himaja\" PersonifyCampaignArn=\"\" FraudDetectorId=\"\" KmsKeyId=\"1813ea5d-cebe-4cf7-9285-5f0408b6a682\" RzpKeyId=\"rzp_test_SMGdQCyn3EUMo5\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
